### ISSUE TITLE
[Discussion] 项目开发相关

### ISSUE THREAD

**Issue by zihengCat** [Yesterday17/Bilibili-Column-Helper#3]
# 问题描述
获取源码，安装依赖，`npm`启动，呈现空白（无内容）。
```
npm run dev
```
![screen shot 2018-04-29 at 12 38 49](https://user-images.githubusercontent.com/19472493/39403302-cf5bc084-4baa-11e8-9b7b-a64ada6a5c57.png)
# 项目建议
完善`README.md`文档，写明用户使用、参与开发的**具体流程**。可以参考[我的这个](https://github.com/zihengCat/bilibili-zhuanlan-markdown-tool)。
# 测试环境
- **OS**: *macOS 10.9.5*
- **Node.js**: *v9.7.1*
# 碎碎念
加装GUI图形界面真是件麻烦的事情呐，又是`electron`又是`vue`的，依赖关系一大堆，核心功能代码又不多。还是命令行好用，只要功能实现，一行`node uplode.js test.md`直接提交Markdown到B站专栏了，虽说CLI可能对小白用户不太友好吧......Orz

**Comment by zihengCat** [comment]
OK，`build`构建之后再安装`.dmg`，项目可以顺利启动！
```
npm run build
```
现在问题变成：**喵不会用这软件啊.....Orz**
![screen shot 2018-04-29 at 13 08 40](https://user-images.githubusercontent.com/19472493/39403432-b8abf30a-4bae-11e8-9f38-4e3df5aafdf1.png)

**Comment by Yesterday17** [comment]
@zihengCat 本项目建议使用yarn，`yarn dev`进入调试，支持热加载。
我去写README休息一下2333

**Comment by zihengCat** [comment]
@Yesterday17 
你现在是搭好了UI界面，功能还没有实现，是么？

**Comment by Yesterday17** [comment]
@zihengCat 
嗯，准确来说是之前完成过一部分，但因为用Vue重构了一次就拆了。。
之前残留的代码主要在[这里](https://github.com/Yesterday17/Bilibili-Column-Helper/tree/master/src/renderer/utils)，[这里](https://github.com/Yesterday17/Bilibili-Column-Helper/blob/master/static/index.html)，[这里](https://github.com/Yesterday17/Bilibili-Column-Helper/blob/master/static/login.html)还有[这里](https://github.com/Yesterday17/Bilibili-Column-Helper/blob/master/main.js)，基本都没法通过ESLint（因为没改过）。

**Comment by zihengCat** [comment]
@Yesterday17 
要不要把我已经写好的功能模块集成到你的项目中去呢？喵有留API接口，给出本地`Markdown`文件路径和`cookies`就能发送了。
```
/*
 * API 说明
 * 参数: Markdown 文档路径, 配置选项
 * 处理流程: 取得 MD 文档与配置选项 -> Markdown 转换 HTML ->
 *           上传文章本地图片至B站 -> 取得B站外链 ->
 *           替换本地图片地址为B站外链地址 -> 合成表单发送更新
 */
biliZhuanlanMarkdown.startProcess (
    "path/to/markdown.md",
    {
      "cookies": "userData",
    }
);
```
你只需要在UI界面上开出一个类似的前端图形接口就可以啦。
![](https://raw.githubusercontent.com/zihengCat/bilibili-zhuanlan-markdown-tool/master/docs/step4_1.png)

**Comment by zihengCat** [comment]
- 为什么要用本地文件路径：因为要处理文章本地图片，在线Markdown不好处理图片...必须保存到本地。
- 为什么用`Cookies`：就是你通过 Bilibili 账户登录，拿到的认证信息。喵偷懒就直接复制粘贴到配置文件，一次大概能用一个月吧23333

**Comment by zihengCat** [comment]
@Yesterday17 
`ESLint`是代码规范性检查？能不能关掉啊...

**Comment by Yesterday17** [comment]
@zihengCat 我开着是规范编码风格的，关了也没事
以及登录的话我还是准备用之前的webview + [https://passport.bilibili.com/ajax/miniLogin/minilogin](https://passport.bilibili.com/ajax/miniLogin/minilogin)，这种用法是从[bilibili-live-helper](https://github.com/pandaGao/bilibili-live-helper)那里学过来的（

**Comment by zihengCat** [comment]
@Yesterday17 
原理一样的，就是为了取得这几枚关键`cookies`，与B站服务器作交互。喵这边是手动将这些`cookies`复制粘贴到一个`json`配置文件中，这样命令行程序也可以读取使用了。
![screen shot 2018-04-29 at 16 14 49](https://user-images.githubusercontent.com/19472493/39404601-9d96be82-4bc8-11e8-9381-2b23ba228bcf.png)

**Comment by Yesterday17** [comment]
@zihengCat 如果有空的话你可以把你的repo传一下npm，这样就直接能够通过包引用了（（

**Comment by zihengCat** [comment]
@Yesterday17 
呃...喵这个项目随便写写的，当时就是看中`marked`才选用`Node.js`。
至于上传到NPM，代码太烂...没考虑过呢...Orz

**Comment by zihengCat** [comment]
@Yesterday17 
已打包上传，这是[NPM地址](https://www.npmjs.com/package/bilibili-zhuanlan-markdown-tool)。
```
npm install bilibili-zhuanlan-markdown-tool
```
测试可用。
![screen shot 2018-04-29 at 18 47 01](https://user-images.githubusercontent.com/19472493/39405774-022a5d6c-4bde-11e8-9f06-6495ff29c2fd.png)

**Comment by zihengCat** [comment]
集成使用的时候一定要用`try...catch...`结构。
因为这个喵写的时候没有写错误检测，任意一个处理环节出现错误，立刻`throw`抛错，程序就终止退出。

**Comment by Yesterday17** [comment]
@zihengCat get√
我估计会用其中的部分吧，不会直接用startProcess

**Comment by zihengCat** [comment]
@Yesterday17 
那我得把API改工整一些，当时想的是只暴露一个接口对外可用的...Orz

**Comment by zihengCat** [comment]
@Yesterday17 
你大概需要实现什么功能，喵看看能不能抽API出来给你调用...现在模块代码内聚性很高，可能跟你期望实现的效果不太一样。

**Comment by Yesterday17** [comment]
@zihengCat 其实感觉能用。。具体需求还得看看，等我一个月以后高考完再弄吧（逃

**Comment by zihengCat** [comment]
@Yesterday17 
高考顺利 :)

**Comment by Yesterday17** [comment]
hmmm 先关了吧（逃
