### ISSUE TITLE
[Bug/建议] 保存新建专栏中的内容 & 压缩图片

### ISSUE THREAD

**Issue by Z-fly** [Yesterday17/Bilibili-Column-Helper#5]
![](https://user-images.githubusercontent.com/10470892/43754317-c6a826fe-9a3c-11e8-94e2-3379ec09d590.png)
此界面填的东西不能保存。
Mac笔记本的触控板不小心点到旁边东西就没了。
上传图片过大或者过小都没有提示，官方是有提示的，建议以后增加压缩图片功能。

**Comment by Yesterday17** [comment]
不能保存是我特意加上去的，hmmm，如果体验不好我先删掉吧。
压缩图片已经加到1.0.0的[Project](https://github.com/Yesterday17/Bilibili-Column-Helper/projects/2)里了，最近填坑加上，咕咕咕（逃

**Comment by Yesterday17** [comment]
压缩图片我之前就放到[Project](https://github.com/Yesterday17/Bilibili-Column-Helper/projects/2)里了，不能保存的问题在最新的[commit](https://github.com/Yesterday17/Bilibili-Column-Helper/commit/de9b146d2c58aa19375641c9eca4c4e20e9d04b5)里解决，先Close了（
